// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbpdypscbcvgvluensai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicGR5cHNjYmN2Z3ZsdWVuc2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzAxMzYsImV4cCI6MjA3MzAwNjEzNn0.dK_9sibBUOl4ELqzr3W5at1I5jns9jVlTwJwRVa6G-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});